### ISSUE TITLE
I cant do the hand presentation event tho i turned it on

### ISSUE THREAD

**Issue by zyroscope** [malaybaku/VMagicMirror#357] opened 2020-08-16 18:28 UTC
![image](https://user-images.githubusercontent.com/52006801/90341324-e136cc80-e028-11ea-8f86-6492e84e7b61.png)

**Comment by malaybaku** [comment] 2020-08-17 05:29
Thank you for feedback,

I cannot point out the cause, but the issue might be fixed in latest version so please try v1.2.0.

Also note that, VMagicMirror supports windows 10 only. The OS looks Windoes 8 (or 8.1) and this might be the cause. Because VMagicMirror uses many Windows API and other native APIs based on latest Windows OS, so older OS can cause some issues.

**Comment by malaybaku** [comment] 2020-10-19 13:04
I am closing this issue, because there are no additional action.

**Closed by malaybaku** 2020-10-19 13:04 UTC
