### ISSUE TITLE
MeowFace Connection stopped working

### ISSUE THREAD

**Issue by porkyoot** [malaybaku/VMagicMirror#886] opened 2023-01-21 11:00 UTC
The connection to the external tracker with MeowFace App worked well for a while but suddenly stopped working. I try reinstalling the apps on the phone and the computer but nothing works. The connection appears in the app like normal but the avatar doessn't move. It works with internal webcam recognition but I want the expressionss to work (even with a key or something).

Is there anything I can do ?

**Comment by malaybaku** [comment] 2023-01-24 16:18
Thanks for feedback.

I have tried to test with my Android device (XPeria 1 III), and confirmed that Meowface shuts down soon after app start in my environment.

It is totally different behavior since last time I checked, and I think I cannot help.

I am now considering to remove doc about Meowface in VMM web page, rather than dealing with this problem...

**Comment by malaybaku** [comment] 2023-01-25 13:46
@porkyoot 
I have merged the PR above to remove help page about MeowFace, at the timing of next VMagicMirror release.

Here is some of the reason why I think the app's tracking system is not enough stable and maintained.

- https://twitter.com/Suvidriel/status/1565038043509231617?s=20&t=kdkX2yUGytywQKpekcX8oQ
- https://twitter.com/Suvidriel/status/1616469587989786624?s=20&t=kdkX2yUGytywQKpekcX8oQ

**Closed by malaybaku** 2023-01-25 13:46 UTC
