### ISSUE TITLE
Settings window not loading

### ISSUE THREAD

**Issue by ichibbnn** [malaybaku/VMagicMirror#742] opened 2022-03-29 00:42 UTC
When I launch VMM v2.0.2, only this window loads up and the settings window does not. Tried restarting and relaunching it again and again but the settings window still does not load. How can this be fixed?

![image](https://user-images.githubusercontent.com/62070635/160509871-b4ce8406-8da0-4937-a431-2c702180fbe9.png)

**Comment by malaybaku** [comment] 2022-03-29 03:55
@ichibbnn It seems anti-virus or zip file corruption issue, please contact to me via BOOTH message system or twitter DM. 

ref: https://malaybaku.github.io/VMagicMirror/en/questions#cannot-start-app-because-zip-file-seems-corrupted

**Comment by malaybaku** [comment] 2022-04-05 05:15
@ichibbnn 
I close this issue, since this I think it is problem caused by download failure.

**Closed by malaybaku** 2022-04-05 05:15 UTC
Labels: question
