### ISSUE TITLE
MirrorRespond

### ISSUE THREAD

**Issue by DemonRem** [malaybaku/VMagicMirror#479] opened 2020-12-12 15:28 UTC
hey @malaybaku 

you think you can do that nice feature on the video he mention that the system can read the brain mind dont know how excely 
but look at that part : https://youtu.be/CvievLytmrs?t=115
full video here:
https://www.youtube.com/watch?v=CvievLytmrs

**Comment by malaybaku** [comment] 2020-12-13 00:48
Hi @DemonRem 
I close this issue, because :

- What they do is so-called face expression analysis. (Not brain machine interface)
- I think It is reproduce of #442 , in which I am considering to use MediaPipe so that user can get better tracking and potentially can reflect facial expression parameters.
- If you mean the feature like "expression changes when user get close to cam", then I want to achieve this by simple improving tracking.

**Closed by malaybaku** 2020-12-13 00:48 UTC

**Comment by DemonRem** [comment] 2020-12-14 02:22
wow @malaybaku you amazing keep the good job!
