### ISSUE TITLE
Feature Requests: LeapMotion and Keybinds for Camera positions, move arms.

### ISSUE THREAD

**Issue by cen0b** [malaybaku/VMagicMirror#729] opened 2022-03-11 23:09 UTC
I would love to have Leap Motion support as an option, (even if its only in the paid version)
as well as keybind support for saved camera positions!

Maybe add a way to move the arms closer to the side of the character?

**Comment by malaybaku** [comment] 2022-03-14 11:46
@cen0b Thanks for request, 

> Leap Motion support as an option

I do not plan and it is by design, because of license condition by Ultraleap and my hardware support policy. Please consider to use Luppet for this point.

> keybind support for saved camera positions

I made separated issue for this: #732 .
The feature must avoid unexpected hot key based behavior, so it may take some time to implement.

> Maybe add a way to move the arms closer to the side of the character?

This is supported and I do not plan further improvement so far. Please check  `Arm` section in following page.

https://malaybaku.github.io/VMagicMirror/en/docs/motion

> add support to move the character with a controller?

Controller based motion is already supported.
If you mean game like motion (e.g. walking or jumping), I do not plan it, and it is by design.

**Comment by malaybaku** [comment] 2022-03-29 11:33
I close this issue, based on separated issue #732 and my reponses about other requests.

**Closed by malaybaku** 2022-03-29 11:33 UTC
Labels: enhancement
